spring.application.name=aprendeaprueba
ia.api.key=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
ia.api.url=https://openrouter.ai/api/v1/chat/completions
ia.model=nvidia/nemotron-nano-12b-v2-vl:free
firebase.database.url=https://aprendeaprueba-667c6-default-rtdb.firebaseio.com/
server.port=${PORT:8080}